# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Teste
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn build
  displayName: 'yarn install and build'

- script: |
    docker build -t diegodesalles/simple-project .
  displayName: 'Build Docker image'

- script: |
    echo "${{ secrets.DOCKER_PW }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin
    docker tag diegodesalles/simple-project diegodesalles/simple-project:latest
    docker push diegodesalles/simple-project:latest
  displayName: 'Deploy to Docker Hub'

- script: |
    ssh -i ~/.ssh/${{ secrets.SSH_PRIVATE_KEY }} azureuser@${{ secrets.AZURE_IP }} << 'EOF'
      sudo docker pull diegodesalles/simple-project:latest
      sudo docker stop simple-project || true
      sudo docker rm simple-project || true
      sudo docker run -d --name simple-project -p 4173:4173 diegodesalles/simple-project:latest
    EOF
  displayName: 'Deploy to Azure VM'
